apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: releaseforge-app
  namespace: releaseforge
  labels:
    app: releaseforge-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: releaseforge-app
  template:
    metadata:
      labels:
        app: releaseforge-app
    spec:
      containers:
        - name: releaseforge-app
          image: subodhmore/releaseforge-app:5348b969e74988fca9c4dda4c8c3840609f2c0d4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "dev"
            - name: SIMULATE_FAILURE
              value: "false"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
  strategy:
    canary:
      stableService: releaseforge-app
      canaryService: releaseforge-app-canary
      trafficRouting:
        nginx:
          stableIngress: releaseforge-ingress
      steps:
        - setWeight: 10
        - pause: {duration: 20}
        - analysis:
            templates:
              - templateName: releaseforge-success-rate
            args:
              - name: service-name
                value: releaseforge-app-canary
        - setWeight: 50
        - pause: {duration: 20}
        - setWeight: 100
