apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: releaseforge-app
  namespace: releaseforge
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: releaseforge-app
  namespaceSelector:
    matchNames:
      - releaseforge
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
